[package]
name = "fuusak"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
derive-new = "0.5"
pest = "2.1"
pest_derive = "2.1"
prettydiff = "0.3"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
walkdir = "2.3"
