[package]
name = "fuusak"
edition = "2018"

version = "0.1.0"

[dependencies]
clap = "2.33"
colorful = "0.2"
derive-new = "0.5"
diff = "0.1"
ignore = "0.4"
notify = "4.0"
pest = "2.1"
pest_derive = "2.1"
rand = "0.7"
regex = "1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"